# Generated by Django 5.2.5 on 2025-08-13 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0001_initial"),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("yes", "Ja"),
                            ("partial", "Teilweise"),
                            ("no", "Nein"),
                        ],
                        max_length=7,
                    ),
                ),
                ("obstacles", models.TextField()),
                ("next_step", models.TextField()),
                ("next_step_source", models.CharField(default="user", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goals.goal"
                    ),
                ),
                (
                    "user_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.usersession",
                    ),
                ),
            ],
        ),
    ]
