# Generated by Django 5.2.5 on 2025-08-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_rename_score_to_overall"),
        ("lessons", "0003_classroom"),
        ("reflections", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reflection",
            constraint=models.UniqueConstraint(
                fields=("goal",), name="unique_reflection_per_goal"
            ),
        ),
    ]
