# Generated by Django 4.2.23 on 2025-08-16 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SRLEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField()),
                ("goal", models.TextField()),
                ("priorities", models.TextField(blank=True)),
                ("strategies", models.TextField(blank=True)),
                ("resources", models.TextField(blank=True)),
                ("time_planning", models.TextField(blank=True)),
                ("expectations", models.TextField(blank=True)),
                ("steps", models.TextField(blank=True)),
                ("time_usage", models.TextField(blank=True)),
                ("strategy_check", models.TextField(blank=True)),
                ("problems", models.TextField(blank=True)),
                ("emotions", models.TextField(blank=True)),
                ("goal_achievement", models.TextField(blank=True)),
                ("strategy_evaluation", models.TextField(blank=True)),
                ("self_assessment", models.TextField(blank=True)),
                ("time_management_reflection", models.TextField(blank=True)),
                ("emotions_reflection", models.TextField(blank=True)),
                ("outlook", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="dashboard.student",
                    ),
                ),
            ],
        ),
    ]
