# Generated by Django 4.2.23 on 2025-08-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudonym", models.CharField(max_length=50)),
                ("login_code", models.CharField(blank=True, max_length=20)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="dashboard.classroom",
                    ),
                ),
            ],
            options={
                "unique_together": {("classroom", "pseudonym")},
            },
        ),
    ]
