# Generated by Django 4.2.23 on 2025-08-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_srlentry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="srlentry",
            name="goal",
        ),
        migrations.AddField(
            model_name="srlentry",
            name="goals",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="srlentry",
            name="goal_achievement",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="srlentry",
            name="priorities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="srlentry",
            name="steps",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="srlentry",
            name="time_planning",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="srlentry",
            name="time_usage",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
