# Generated by Django 4.2.23 on 2025-08-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_srlentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_date", models.DateField()),
                ("strategies", models.TextField(blank=True)),
                ("resources", models.TextField(blank=True)),
                ("expectations", models.TextField(blank=True)),
                ("steps", models.TextField(blank=True)),
                ("strategy_check", models.TextField(blank=True)),
                ("problems", models.TextField(blank=True)),
                ("emotions_execution", models.TextField(blank=True)),
                ("strategy_evaluation", models.TextField(blank=True)),
                ("self_assessment", models.TextField(blank=True)),
                ("time_management_reflection", models.TextField(blank=True)),
                ("emotions_reflection", models.TextField(blank=True)),
                ("outlook", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="dashboard.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("high_priority", models.BooleanField(default=False)),
                ("planned_time", models.DurationField(default=0)),
                ("engaged", models.BooleanField(default=False)),
                ("actual_time", models.DurationField(default=0)),
                (
                    "achievement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vollständig", "vollständig"),
                            ("teilweise", "teilweise"),
                            ("nicht", "nicht"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="dashboard.dayentry",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.DeleteModel(
            name="SRLEntry",
        ),
    ]
