# Generated by Django 4.2.23 on 2025-08-16 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_srlentry_goal_srlentry_goals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="srlentry",
            name="expectations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="srlentry",
            name="resources",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="srlentry",
            name="session_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="srlentry",
            name="strategies",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
