# Generated by Django 4.2.23 on 2025-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0004_alter_srlentry_expectations_alter_srlentry_resources_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="srlentry",
            name="strategy_check",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
