# Generated by Django 4.2.23 on 2025-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_srlentry_strategy_check"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="srlentry",
            name="emotions_reflection",
        ),
        migrations.RemoveField(
            model_name="srlentry",
            name="outlook",
        ),
        migrations.RemoveField(
            model_name="srlentry",
            name="self_assessment",
        ),
        migrations.RemoveField(
            model_name="srlentry",
            name="time_management_reflection",
        ),
        migrations.AddField(
            model_name="srlentry",
            name="learned_subject",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="srlentry",
            name="learned_work",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="srlentry",
            name="motivation_improve",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="srlentry",
            name="motivation_rating",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="srlentry",
            name="next_phase",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="srlentry",
            name="planning_deviations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="srlentry",
            name="planning_realistic",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="srlentry",
            name="strategy_outlook",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="srlentry",
            name="strategy_evaluation",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
