# Generated by Django 4.2.23 on 2025-08-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_appsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="overall_goal_due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
