# Generated by Django 4.2.23 on 2025-08-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_student_overall_goal_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="max_entries_per_day",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="max_entries_per_week",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)],
                default=1,
            ),
        ),
    ]
