# Generated by Django 4.2.23 on 2025-08-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_classroom_max_entries_per_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="max_planning_execution_minutes",
            field=models.PositiveSmallIntegerField(default=90),
        ),
    ]
