# Generated by Django 4.2.23 on 2025-08-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_classroom_max_planning_execution_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
