# Generated by Django 4.2.23 on 2025-08-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_student_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="openai_model",
            field=models.CharField(default="gpt-4o-mini", max_length=100),
        ),
    ]
