# Generated by Django 4.2.24 on 2025-09-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_appsettings_openai_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentalReflectionChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_achievement", models.BooleanField(default=False)),
                ("strategy_evaluation", models.BooleanField(default=False)),
                ("learned_subject", models.BooleanField(default=False)),
                ("learned_work", models.BooleanField(default=False)),
                ("planning_realistic", models.BooleanField(default=False)),
                ("planning_deviations", models.BooleanField(default=False)),
                ("motivation_rating", models.BooleanField(default=False)),
                ("motivation_improve", models.BooleanField(default=False)),
                ("next_phase", models.BooleanField(default=False)),
                ("strategy_outlook", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflection_changes",
                        to="dashboard.srlentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperimentalPlanningChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goals", models.BooleanField(default=False)),
                ("priorities", models.BooleanField(default=False)),
                ("strategies", models.BooleanField(default=False)),
                ("resources", models.BooleanField(default=False)),
                ("time_planning", models.BooleanField(default=False)),
                ("expectations", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_changes",
                        to="dashboard.srlentry",
                    ),
                ),
            ],
        ),
    ]
