# Generated by Django 5.2.5 on 2025-08-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonsession",
            name="use_ai",
            field=models.BooleanField(default=False),
        ),
    ]
